name: Release VS Code Extension

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  release-job:
    name: "Release VS Code Extension"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "win32-arm64",
            "win32-x64",
            "linux-arm64",
            "linux-x64",
            "linux-armhf",
            "alpine-x64",
            "darwin-x64",
            "darwin-arm64",
            "alpine-arm64",
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify version match
        run: |
          # Get version from package.json
          PKG_VERSION=$(node -p "require('./package.json').version")

          # Get release version
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}

          echo "Package.json version: $PKG_VERSION"
          echo "Release version: $RELEASE_VERSION"

          # Check if package.json version matches release version
          if [ "$PKG_VERSION" != "$RELEASE_VERSION" ]; then
            echo "Error: Version mismatch!"
            echo "package.json version ($PKG_VERSION) does not match release version ($RELEASE_VERSION)"
            exit 1
          fi

      - name: Install dependencies
        run: npm install

      - name: Checking Linting
        run: npm run lint

      - name: Compile Extension
        run: npm run package -- --target ${{ matrix.platform }}

      - name: Package extension
        run: npx vsce package --target ${{ matrix.platform }} --out "oopilot-${{ matrix.platform }}.vsix"

      - name: Upload extension vsix as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "oopilot-${{ matrix.platform }}.vsix"
          path: "oopilot-${{ matrix.platform }}.vsix"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "oopilot-${{ matrix.platform }}.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
